In [1]:
#Import numpy library
import numpy as np

#Set seed for reproducability
np.random.seed(100)

We will now proceed to calculate a fitness function that helps us select the best solutions in any population. 

This fitness function will be the addition of all the inputs times weight in our population. 

In [2]:
#Calcuate fitness of population

def calculate_fitness(inputs, population):
    
    '''
    Description: This function calculates the fitness of our solutions
    
    Input Arguments: input values and a population of weights
    
    Output: Fitness - a fitness value
    
    '''
    
    fitness = np.sum(population*inputs, axis=1)
    return fitness

Next, we proceed to choose parents that will mate. This involves choosing the most fit parents in the population according to our fitness value

In [3]:

#Choose parents to mate 

def choose_mating(population, fitness, number_of_parents):
    
    '''
    Description: This function chooses the most fit solutions to mate in order to yield the next generation
    
    Input Arguments: a population, the fitness and the number of parents required to mate
    
    Output: 
    
    the parents to mate
    '''
    
    #initialize empty numpy array to hold parents
    parents = np.empty((number_of_parents, population.shape[1]))
    
    #loop to fill the created parents array with the fittest solutions and stop at the required number of parents
    for number in range(number_of_parents):
        maximum_fitness_index = np.where(fitness == np.max(fitness))
        maximum_fitness_index = maximum_fitness_index[0][0]
        parents[number, :] = population[maximum_fitness_index, :]
        fitness[maximum_fitness_index] = -99999999999
        
    
    return parents

We will now proceed to perform a one point cross over on the parent pool at the center

In [4]:
#Perform cross over

def crossingover(parents, size_of_offspring):
    '''
    Description: This function performs a one point cross over operation on the parents. 
    
    Input Arguments:
    Parents - the parents pool to be crossed over
    size of offspring - the size of offspring required
    
    Output: 
    
    offspring - the crossed over offspring
    '''
    # initialize an empty numpy array to hold the offsprings
    offspring = np.empty(size_of_offspring)
    
    # specify the point of cross over - at the center in our case
    point_of_crossover = np.uint8(size_of_offspring[1]/2)
    
    #loop over the number of offspring required to get the required offsprings
    
    for k in range(size_of_offspring[0]):
        # get index of first parent to be mated
        parent1_index = k%parents.shape[0]
        # get index of second parent to be mated
        parent2_index = (k+1)%parents.shape[0]
        # proceed to assign the first half of the first parents gene to the first half gene of the offspring
        offspring[k, 0:point_of_crossover] = parents[parent1_index, 0:point_of_crossover]
        # proceed to assign the second half of the second parents gene to the second half gene of the offspring
        offspring[k, point_of_crossover:] = parents[parent2_index, point_of_crossover:]
        
    return offspring

Next, we proceed to change a single gene in each  offspring in a random manner so as to induce randomness in the whole process. This is called mutation. 

In [5]:
#perform mutation

def mutation(cross_over_offspring):
    
    '''
    Description: This function performs some random variation to the genes of the 
    solutions by adding a random bias number.
    
    Input - 
    cross_over_offspring - offspring obtained from the cross over function
    
    Output -
    Mutated offspring 
    
    '''
    
    #loop over the offsprings and add a random bias number to their genes
    for number in range(cross_over_offspring.shape[0]):
        # Create the random bias number to be used for muation. The arguments taken are the limits(low and high) and the size
        random_bias_number = np.random.uniform(-1.5, 1.5, 1)
        
        #Proceed to mutate by adding the bias number
        
        cross_over_offspring[number, 3] = cross_over_offspring[number, 3] + random_bias_number
    return cross_over_offspring

## Proceed to Implement Genetic Algorithm 

We will now proceed to perform the genetic algorithm on a simple example function by aiming to maximize it. 

This equation is given as $F(X) = A1X1 + A2X2 + A3X3 + A4X4$

Where X1 = 4
      X2 = -2
      X3 = 3.5
      X4 = -4.2
 All randomly chosen. 

We will be looking to optimize the values - A1, A2, A3 and A4 in order to maximize the function F(X)

We will begin with a set of inputs of X and then specify the number of weights. Then we specify a number of generations to mate through and the best solutions are chosen at the end. 

The functions created earlier will be combined to create the Genetic Algorithm that will help us yield the maximum over the generations specified. 

In [6]:

'''
Implementing the GA

'''
# Specify inputs of the equation ( X values)
inputs = [4,-2,3.5,-4.2]

# Specify the number of weights or multipliers (A values, in our case) for each input which we are looking to optimize
number_of_weights = 4

# Specify the number of solutions in each generation. Each solution will have the number of weights
solutions = 6

#Specify the number of parents mating to yield the specified number of solutions
number_of_parents_mating = 3

# Define the population size based on the number of parents mating and the number of solutions
population_size = (solutions,number_of_weights)

#randomly create the inital population according to the specified population size
new_population = np.random.uniform(low=-5.0, high=5.0, size=population_size)

#Print out the initialized population
print(new_population)


#Specify the number of generations to mutate through 
number_of_generations = 10

#Loop over the specified number of generations

for generation in range(number_of_generations):
    
    #Print the generation in which we are currently looping through to keep track
    print("Generation : ", generation)
    
    # Calculate the fitness of the population in the current generation
    fitness = calculate_fitness(inputs, new_population)

    # Proceed to select the most fit parents to mate
    parents = choose_mating(new_population, fitness, 
                                      number_of_parents_mating)

    # Proceed to create offsprings via the one point cross over
    crossover = crossingover(parents,
                                       size_of_offspring=(population_size[0]-parents.shape[0], number_of_weights))

    # Proceed to add random bias to the genes of the created offspring via the mutation function
    mutated = mutation(crossover)

    # Proceed to create the new population from the parents and the mutated
    new_population[0:parents.shape[0], :] = parents
    new_population[parents.shape[0]:, :] = mutated

    # Get the best or most fit solution in this current generation
    print("Best result : ", np.max(np.sum(new_population*inputs, axis=1)))




[[ 0.43404942 -2.21630615 -0.75482409  3.44776132]
 [-4.95281144 -3.78430879  1.70749085  3.25852755]
 [-3.6329341   0.75093329  3.91321954 -2.90797878]
 [-3.1467178  -3.9162311  -2.80302507  4.78623785]
 [ 3.11683149 -3.28058987  3.16224749 -2.25926253]
 [-0.68295816  4.4002982   3.17649379 -1.6388805 ]]
Generation :  0
Best result :  49.028113263774884
Generation :  1
Best result :  49.028113263774884
Generation :  2
Best result :  54.00325242758298
Generation :  3
Best result :  54.00325242758298
Generation :  4
Best result :  54.62879766910555
Generation :  5
Best result :  54.62879766910555
Generation :  6
Best result :  59.076760471603336
Generation :  7
Best result :  62.218000584459546
Generation :  8
Best result :  62.218000584459546
Generation :  9
Best result :  62.218000584459546


We will now proceed to obtain the best solution after all generations. We will do this by calculating the fitness of all the solutions in the final generation and then returning the most fit solution amongst all of this. 

In [7]:
#Calculate fitness of final generation
fitness = calculate_fitness(inputs, new_population)

# Get most fit solution of final generation
most_fit_index = np.where(fitness == np.max(fitness))

#Print out the best solution 
print("Best solution : ", new_population[most_fit_index, :])
print("Best solution fitness : ", fitness[most_fit_index])

Best solution :  [[[ 3.11683149 -3.28058987  3.91321954 -7.02219678]]]
Best solution fitness :  [62.21800058]


There you have it, genetic algorithm simplified from scratch. 